name: sonarqube scan test
on:
  push:
      branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    # 如果是Maven
    - name: Build and analyze with Maven
      run: mvn clean verify sonar:sonar -Dsonar.projectKey=my_scan_demo -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }} -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
