name: sonarqube scan
on:
  push:
      branches: [ main ]
jobs:
  build:

    runs-on: my_runner

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # 如果是Maven
    - name: Build and analyze with Maven
      run: mvn clean verify sonar:sonar -Dsonar.projectKey=${{ github.event.repository.name }} -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }} -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
