name: sonarqube scan
on:
  push:
      branches: [ main ]
jobs:
  sonarQubeTrigger:
    runs-on: ubuntu-latest
    steps:
    - name: SonarQube Scan
    - uses: monstar-lab-oss/sonarqube-github-action@v1.0.1
      with:
        url: ${{ secrets.SONARQUBE_HOST }}
        token: ${{ secrets.SONARQUBE_TOKEN }}
