name: ssh connect
on:
  push:
      branches: [ main ]
  #pull_request_target: 
jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: ssh config
        id: action-ssh
        uses: tiyee/action-ssh@main
        with:
          host: 47.243.86.137 
          port: 22 
          username: root 
          privateKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC99e6dsA8VNbnASnPBGhwspmIGo3aKRXtH70E05J6WefGbDPTB5G5BoXMYfiTroEkbPiWhBZqDXWeeOu9SqPOwKhxef2hZR8Wu83obFYKfgjjZtdBllCCxVZORImvx0xxn4dnBFDTwjGFaIWNHYVb5wXsVoqitCh0A2y0mvxQx5ouJZsgJNWwlD52m94EzcUHYcbYCrnjAaKudPi7ZhX3a1qXq55NO3gQbSsrYNFXeRIi9AVAmOCuBy5Dbrne0W9FTyer2WSI+mvM6bmPI5g6cS6XHsZ2yklGESI1kSKTnnjHLE6MB9Fb1piBsWIECZjTySN+KZhM0AC6yL/L+4S2bSvZ72zxDADV7FjRUCVEFsVdEmUrvjomdbc8AsS+cWDMqsl6rE0nPMIyegPvVmHltHWxLpDPQEmwGmLeoDsgX2wDq/mZNs556VExm7dYRHtIgWQJeKGoOyc+pBIcvBX5eRfbtDWF6h27cK0Nqk7/TTPtNQ4gZcvWDDNw5dyA7pwaeBdAcZeI/i6KVv+QzeB0KkwdtXHyJABqSeukpc0XgpKcUV4lrqEPvbMSDCubxdV0dfjrmsuyyiDMcIziZAkgFqRV2DSBLkWd5h4jt79EM/UUBmaeMVH0JK1jpOumO7xwhqeQFo6g0o+cGFuK/OJ6+ElluE2XDMwak/xNWXfzhtQ== root@sofastack-hk
          command: 'ls -alh'
