name: ssh connect
on:
  push:
      branches: [ main ]
  #pull_request_target: 
jobs:
  #  # stc作业使用了ubuntu-latest作为运行环境，包含了一个步骤（steps）codeScan，该步骤使用了layotto/alipay-cloud-devops-codescan@main作为GitHub Action，并传入了一些参数（parent_uid、private_key、code_type）
  ssh:   # 安全扫描
    runs-on: ubuntu-latest
    steps:
      - name: ssh connect
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "47.243.86.137 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBOX3WFD3T3IQijKLyLs4qe8J4OEll+b2o7xoE6ps+3H" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          ls -a
      - name: ssh
        run: |
          ssh root@47.243.86.137
