name: ssh c
on:
  push:
      branches: [ main ]
jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: ssh config
        id: action-ssh
        uses: tiyee/action-ssh@main
        with:
          host: 140.205.117.80
          port: 22 
          username: hu 
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          command: 'ls -alh'
