name: ssh connect
on:
  push:
      branches: [ main ]
jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: ssh config
        id: action-ssh
        uses: tiyee/action-ssh@main
        with:
          host: 47.111.138.11
          port: 22 
          username: root 
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          command: 'ls -alh'
