name: Alipay Cloud Devops Codescan
on:
  push:
      branches: [ main ]
  #pull_request_target: 
jobs:
  #  # stc作业使用了ubuntu-latest作为运行环境，包含了一个步骤（steps）codeScan，该步骤使用了layotto/alipay-cloud-devops-codescan@main作为GitHub Action，并传入了一些参数（parent_uid、private_key、code_type）
  ssh:   # 安全扫描
    runs-on: ubuntu-latest
    steps:
      - name: ssh connect
        run: |
          ls -a
